version: "3.7"

services:
  database:
    container_name: postgres
    image: postgres
    volumes:
      - /path/to/postgresql-persistence:/bitnami/postgresql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=classroom
    ports:
      - "6432:5432"
  app:
    container_name: apirest_classroom
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/classroom

